### ISSUE TITLE
Program request: HMM grapher

### ISSUE THREAD

**Issue by iankorf** [KorfLab/grimoire#16]
We need a program that can read in an grimoire.hmm object and display a graph of what it looks like.

**Comment by amkram** [comment]
Looked into this a bit. A couple options: networkx + matplotlib (Simple basic graph, doesn't show fancy things like self-directed arrows).  Graphviz python package can do cooler things, but requires graphviz to be installed locally. Or something more D.I.Y. Not sure how much we want in terms of dependencies

**Comment by iankorf** [comment]
Good question (about dependancies). I think it's okay to have local dependancies on something like this because it isn't going to be used very often by users, just developers.

**Comment by iankorf** [comment]
Solved with graphviz. Thanks Joy and Alex
