### ISSUE TITLE
random_seq doesn't follow our standards

### ISSUE THREAD

**Issue by iankorf** [KorfLab/grimoire#18]
All scripts need to have argparse command line processing.

The script should probably use classes rather than raw json->dict.

**Comment by JackSSK** [comment]
Sorry! I have tried to corrected the script.
I suppose I could use **HMM.read** in **hmm.py** to read in hmm model from json file; however, I had some errors:

Traceback (most recent call last):
  File "random_seq", line 45, in <module>
    Model = HMM.read(filename = arg.source)
  File "/usr/local/lib/python3.6/dist-packages/grimoire/hmm.py", line 204, in read
    d = json.loads(fp.read())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 9 (char 29)

It seems like problem is about using load function in build-in JSON package, and I am not so sure what should I do with this. 
So I tested my code by simply reading in toy hmm, everything else should be working.
I also tried to use script **forge** to build up a toy hmm model, but it could not run on my machine.
Should I try to fix that up?

**Comment by iankorf** [comment]
I removed toy.hmm from the repo as it was just a bit too simple. The test code creates an HMM that would be acceptable but it currently doesn't save that file. But it should as a form of unit test. I'll add that.

**Comment by JackSSK** [comment]
Thanks! Have updated random_seq, and it should be functional now

**Comment by iankorf** [comment]
I tried it. The problem is that it doesn't report the sequence or annotation in a standard format. I'll fix it.

**Comment by iankorf** [comment]
Instead of fixing the code, I checked in 'emitter', which is my idea of what the sequence generator should look like. It always emits a constant length sequence even if it breaks terminal probabilities. So it's not fully featured. But you might look how it reports the data in fasta plus gff.

**Comment by JackSSK** [comment]
Sure thing!

2019年7月11日(木) 12:21 Ian Korf <notifications@github.com>:

**Comment by JackSSK** [comment]
Fixed up the output format issue. 
About the terminal probability feature, should I simply ask user to setup one (probably in log?) and keep on comparing whether the probability of having a sequence generated so far reaches the setup limit during generation? 
In this case, I think we could give few options to users:
1. Once reached terminal probability, discard the current one and start to generate another. User could set up how many trails are acceptable.
2. Once reached terminal probability, just output what the generator has so far even not shorter than desired.

**Comment by iankorf** [comment]
Not sure it's worth doing the more complicated way
