### ISSUE TITLE
chromosome map

### ISSUE THREAD

**Issue by iankorf** [KorfLab/grimoire#21]
TAIR10 does the annoying thing of having different names in the fasta and gff. There is an example of a map file but there is no class for that, so the code to read it is in forge and fathom. I don't even know if I like this whole idea for one problem case. Maybe better to munge the source data and demand that all names match each other.

**Comment by JackSSK** [comment]
I surely agree that is annoying! 
We could do something like match the names based on similarities and inform the user whether program did it or not, but I don’t think feature like this is demanded nor necessary.

**Comment by iankorf** [comment]
The code will report mis-matched names and throw an exception.

**Comment by iankorf** [comment]
I've removed all the code for mapping mis-matched chromosome names. We will probably have to pre-process some files anyway.
